apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-wallet-deployment
  labels:
    app: web-wallet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-wallet
  template:
    metadata:
      labels:
        app: web-wallet
    spec:
      containers:
        - name: web-wallet
          image: sanjanaynvsdl/web-based-wallet:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
